name: ZjazdowniaRPG
main: eu.zjazdownia.rpg.ZjazdowniaRPG
version: 1.0.0
api-version: "1.20"
author: zjazdownia
website: https://zjazdownia.eu

commands:
  konto:
    description: Otwiera GUI wyboru konta.
    usage: /konto
  klasa:
    description: Otwiera kreator klasy (jeśli konto puste).
    usage: /klasa
  resetkonto:
    description: Resetuje dane podanego gracza lub jeżeli nie wpiszemy gracza to resetuje konto osoby wysyłającej.
    usage: /resetkonto <gracz>
    permission: zjazdownia.admin
  zradmin:
    description: Komenda administracyjna dla ZjazdowniaRPG.
    usage: /zradmin <sub>
    permission: zjazdownia.admin

permissions:
  zjazdownia.account.2:
    description: Odblokowuje drugie konto (premium).
    default: false
  zjazdownia.admin:
    description: Uprawnienia administracyjne do RPG.
    default: op
